//
//  Created by Brian Ganninger on 9/30/16.
//  Copyright © 2016 Atlassian. All rights reserved.
//

@import Foundation;

#import <Sparkle/Sparkle.h>

extern NSString* _Nonnull const PRGUpdateGroupDefaultsKey;
extern NSString* _Nonnull const PRGUpdateVersionDefaultsKey;
extern NSString* _Nonnull const PRGUpdateExemptionDefaultsKey;

@interface PRGUpdateHelper : NSObject <SUUpdaterDelegate>

/*!
 * @discussion Property that disables automatic update checks. Useful during blocking workflows such as setup.
 */
@property (nonatomic, assign) BOOL canUpdate;

/*!
 * @discussion Records when the last check for updates happened. Null if it has not occurred yet.
 */
@property (readonly, nullable, nonatomic, copy) NSDate* lastCheckedForUpdates;

/*!
 * @discussion Latest available version based on last update check. Null if check has not occurred yet.
 */
@property (readonly, nullable, nonatomic, copy) NSString* latestAvailableVersion;

/*!
 * @discussion Reset the current update group if a new version of the app [ex: 2.3.1 -> 2.4] is detected and it's been more than one revision since the last reset. Doesn't apply to alpha or beta releases (determined by the Appcast's suffix.)
 */
+ (void)resetUpdateGrouping;

/*!
 * @discussion Return a predictable grouping for a machine based on provided values.
 * @param uuid An NSUUID instance for randomization purposes.
 * @return NSUInteger Specific update grouping, based on a randomized percentage.
 */
+ (NSUInteger)groupForUUID:(nonnull NSUUID *)uuid;

/*!
 * @discussion Get the appropriate Sparkle Appcast XML feed URL based on rollout group.
 * @param groupNum Specific group number generated by -groupForUUID: (valid values: 0-5)
 * @return NSString Guaranteed to return a string URL for a feed.
 */
- (nonnull NSString *)feedURLForGroup:(NSInteger)groupNum;

/*!
 * @discussion Configures and returns a Sparkle updater for use with this helper.
 * @return SUUpdater New Sparkle updater instance; do not modify its delegate!
 */
- (nonnull SUUpdater *)newSparkleUpdater;

/*!
 * @discussion Accessor for the currently assigned update group.
 * @return NSInteger Integer value representing the update group (valid values: 0-5)
 */
+ (NSInteger)currentUpdateGroup;

@end
